version: '3.8'

services:
  geosuscetibilidade:
    build: .
    container_name: geosuscetibilidade_app
    ports:
      - "80:8080"
    environment:
      - PORT=8080
    deploy:
      resources:
        limits:
          memory: 16g
    # Usa tmpfs para storage para evitar que o servidor encha o disco
    # com o tempo de arquivos de sessão gerados
    tmpfs:
      - /app/storage:size=8G
    restart: always
